using Xceed.Document.NET;
using Xceed.Words.NET;

namespace CodeLensAI.Core;

/// <summary>
/// Generates a professional .docx documentation file from scan results.
/// </summary>
public static class WordExporter
{
    private const string MonospaceFont = "Courier New";
    private const double MonospaceSize = 9d;

    /// <summary>
    /// Writes a complete project documentation document to <paramref name="outputPath"/>.
    /// </summary>
    public static void Export(string outputPath, string projectFolderPath, List<ParseResult> parseResults)
    {
        var projectName = Path.GetFileName(
            projectFolderPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));

        using var document = DocX.Create(outputPath);

        document.AddFooters();
        document.Footers.Odd.PageNumbers = true;

        WriteCoverPage(document, projectName, parseResults);
        document.InsertParagraph().InsertPageBreakAfterSelf();

        WriteTableOfContents(document, parseResults);
        document.InsertParagraph().InsertPageBreakAfterSelf();

        var isFirstClassInDocument = true;
        foreach (var parseResult in parseResults)
        {
            WriteFileSection(document, parseResult, ref isFirstClassInDocument);
        }

        document.Save();
    }

    private static void WriteCoverPage(DocX document, string projectName, List<ParseResult> parseResults)
    {
        document.InsertParagraph(projectName)
            .FontSize(28)
            .Bold()
            .SpacingAfter(12d);

        document.InsertParagraph("Generated by CodeLens AI")
            .FontSize(14)
            .SpacingAfter(8d);

        document.InsertParagraph($"Generated on {DateTime.Now:MMMM d, yyyy 'at' h:mm tt}")
            .FontSize(11)
            .SpacingAfter(24d);

        var stats = ComputeStats(parseResults);

        document.InsertParagraph("Summary")
            .Heading(HeadingType.Heading2)
            .SpacingAfter(8d);

        document.InsertParagraph($"Files scanned: {stats.FileCount}")
            .SpacingAfter(4d);
        document.InsertParagraph($"Classes found: {stats.ClassCount}")
            .SpacingAfter(4d);
        document.InsertParagraph($"Functions found: {stats.MethodCount}")
            .SpacingAfter(16d);

        document.InsertParagraph("Class Breakdown by Category")
            .Heading(HeadingType.Heading2)
            .SpacingAfter(8d);

        var table = document.AddTable(4, 2);
        table.Design = TableDesign.TableGrid;
        table.Alignment = Alignment.center;

        SetTableCell(table, 0, 0, "Category", bold: true);
        SetTableCell(table, 0, 1, "Count", bold: true);
        SetTableCell(table, 1, 0, "Business Logic");
        SetTableCell(table, 1, 1, stats.BusinessLogicCount.ToString());
        SetTableCell(table, 2, 0, "GUI Logic");
        SetTableCell(table, 2, 1, stats.GuiLogicCount.ToString());
        SetTableCell(table, 3, 0, "Utility");
        SetTableCell(table, 3, 1, stats.UtilityCount.ToString());

        document.InsertTable(table);
    }

    private static void WriteTableOfContents(DocX document, List<ParseResult> parseResults)
    {
        document.InsertParagraph("Table of Contents")
            .Heading(HeadingType.Heading1)
            .SpacingAfter(12d);

        foreach (var parseResult in parseResults)
        {
            var fileName = Path.GetFileName(parseResult.FilePath);
            document.InsertParagraph(fileName)
                .Bold()
                .SpacingAfter(2d);

            if (IsCppFile(parseResult.FilePath))
            {
                document.InsertParagraph("    (C++ — parsing not yet implemented)")
                    .Italic()
                    .SpacingAfter(6d);
                continue;
            }

            if (parseResult.Classes.Count == 0)
            {
                document.InsertParagraph("    (no classes)")
                    .Italic()
                    .SpacingAfter(6d);
                continue;
            }

            foreach (var classInfo in parseResult.Classes)
            {
                document.InsertParagraph($"    {classInfo.Name} [{DescribeCategory(classInfo.Category)}]")
                    .SpacingAfter(2d);
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }
    }

    private static void WriteFileSection(DocX document, ParseResult parseResult, ref bool isFirstClassInDocument)
    {
        var fileName = Path.GetFileName(parseResult.FilePath);
        var isCpp = IsCppFile(parseResult.FilePath);

        document.InsertParagraph(fileName)
            .Heading(HeadingType.Heading1)
            .SpacingBefore(12d)
            .SpacingAfter(4d);

        document.InsertParagraph(isCpp ? "[C++]" : "[C#]")
            .Bold()
            .SpacingAfter(8d);

        if (isCpp)
        {
            document.InsertParagraph("C++ parsing not yet implemented.")
                .Italic()
                .SpacingAfter(16d);
            return;
        }

        if (parseResult.Errors.Count > 0)
        {
            document.InsertParagraph($"Parse error: {string.Join("; ", parseResult.Errors)}")
                .SpacingAfter(16d);
            return;
        }

        for (var i = 0; i < parseResult.Classes.Count; i++)
        {
            if (!isFirstClassInDocument)
            {
                WriteClassDivider(document);
            }

            isFirstClassInDocument = false;
            WriteClassSection(document, parseResult.Classes[i]);
        }
    }

    private static void WriteClassSection(DocX document, ClassInfo classInfo)
    {
        document.InsertParagraph(classInfo.Name)
            .Heading(HeadingType.Heading2)
            .SpacingBefore(8d)
            .SpacingAfter(6d);

        document.InsertParagraph($"[{DescribeCategory(classInfo.Category)}]")
            .SpacingAfter(4d);

        document.InsertParagraph(
                string.IsNullOrEmpty(classInfo.BaseClassName)
                    ? "Extends: No base class"
                    : $"Extends: {classInfo.BaseClassName}")
            .SpacingAfter(4d);

        document.InsertParagraph(
                classInfo.ImplementedInterfaces.Count > 0
                    ? $"Implements: {string.Join(", ", classInfo.ImplementedInterfaces)}"
                    : "Implements: None")
            .SpacingAfter(4d);

        document.InsertParagraph(
                classInfo.Dependencies.Count > 0
                    ? $"Depends on: {string.Join(", ", classInfo.Dependencies)}"
                    : "Depends on: None")
            .SpacingAfter(6d);

        if (!string.IsNullOrWhiteSpace(classInfo.XmlSummary))
        {
            document.InsertParagraph(classInfo.XmlSummary)
                .SpacingAfter(8d);
        }

        foreach (var method in classInfo.Methods)
        {
            WriteMethodSection(document, method);
        }
    }

    private static void WriteMethodSection(DocX document, MethodInfo method)
    {
        var signature = BuildSignature(method);

        document.InsertParagraph(signature)
            .Heading(HeadingType.Heading3)
            .Font(MonospaceFont)
            .FontSize(MonospaceSize)
            .SpacingBefore(10d)
            .SpacingAfter(4d);

        document.InsertParagraph($"Access: {method.AccessModifier}")
            .SpacingAfter(6d);

        document.InsertParagraph("Parameters")
            .Bold()
            .SpacingAfter(4d);

        if (method.Parameters.Count == 0)
        {
            document.InsertParagraph("This function takes no inputs.")
                .SpacingAfter(6d);
        }
        else
        {
            foreach (var parameter in method.Parameters)
            {
                var (type, name) = SplitParameter(parameter);
                var paramLine = document.InsertParagraph()
                    .SpacingAfter(2d);
                paramLine.Append($"{type} ").Font(MonospaceFont).FontSize(MonospaceSize);
                paramLine.Append(name).Bold();

                if (method.XmlDocTags.TryGetValue($"param:{name}", out var paramDoc))
                {
                    document.InsertParagraph(paramDoc)
                        .SpacingAfter(4d);
                }
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        document.InsertParagraph("Returns")
            .Bold()
            .SpacingAfter(4d);

        var returnsLine = document.InsertParagraph()
            .SpacingAfter(2d);
        returnsLine.Append(method.ReturnType).Font(MonospaceFont).FontSize(MonospaceSize);

        if (method.XmlDocTags.TryGetValue("returns", out var returnsDoc))
        {
            document.InsertParagraph(returnsDoc)
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(6d);
        }

        document.InsertParagraph("Error Situations")
            .Bold()
            .SpacingAfter(4d);

        if (method.ThrownExceptions.Count > 0)
        {
            foreach (var exception in method.ThrownExceptions)
            {
                document.InsertParagraph($"• {exception}")
                    .SpacingAfter(2d);
            }
        }
        else
        {
            document.InsertParagraph("No exceptions detected.")
                .SpacingAfter(6d);
        }

        if (!string.IsNullOrWhiteSpace(method.XmlSummary))
        {
            document.InsertParagraph(method.XmlSummary)
                .SpacingAfter(6d);
        }

        document.InsertParagraph("[AI Explanation: will be populated once local model is loaded]")
            .Italic()
            .SpacingAfter(12d);
    }

    private static void WriteClassDivider(DocX document)
    {
        document.InsertParagraph("────────────────────────────────────────")
            .FontSize(8d)
            .SpacingBefore(16d)
            .SpacingAfter(16d);
    }

    private static void SetTableCell(Table table, int row, int column, string text, bool bold = false)
    {
        var paragraph = table.Rows[row].Cells[column].Paragraphs[0];
        paragraph.RemoveText(0);
        var formatted = paragraph.Append(text);
        if (bold)
        {
            formatted.Bold();
        }
    }

    private static (int FileCount, int ClassCount, int MethodCount, int BusinessLogicCount, int GuiLogicCount, int UtilityCount)
        ComputeStats(List<ParseResult> parseResults)
    {
        var classCount = 0;
        var methodCount = 0;
        var businessLogic = 0;
        var guiLogic = 0;
        var utility = 0;

        foreach (var parseResult in parseResults)
        {
            if (IsCppFile(parseResult.FilePath))
            {
                continue;
            }

            foreach (var classInfo in parseResult.Classes)
            {
                classCount++;
                methodCount += classInfo.Methods.Count;

                switch (classInfo.Category)
                {
                    case CodeCategory.GuiLogic:
                        guiLogic++;
                        break;
                    case CodeCategory.Utility:
                        utility++;
                        break;
                    default:
                        businessLogic++;
                        break;
                }
            }
        }

        return (parseResults.Count, classCount, methodCount, businessLogic, guiLogic, utility);
    }

    private static string BuildSignature(MethodInfo method)
    {
        var parameters = method.Parameters.Count > 0
            ? string.Join(", ", method.Parameters)
            : string.Empty;
        return $"{method.ReturnType} {method.Name}({parameters})";
    }

    private static (string Type, string Name) SplitParameter(string parameter)
    {
        var lastSpace = parameter.LastIndexOf(' ');
        if (lastSpace <= 0 || lastSpace >= parameter.Length - 1)
        {
            return (parameter, "value");
        }

        return (parameter[..lastSpace].Trim(), parameter[(lastSpace + 1)..].Trim());
    }

    private static bool IsCppFile(string filePath) =>
        string.Equals(Path.GetExtension(filePath), ".cpp", StringComparison.OrdinalIgnoreCase);

    private static string DescribeCategory(CodeCategory category) => category switch
    {
        CodeCategory.GuiLogic => "GUI Logic",
        CodeCategory.Utility => "Utility",
        _ => "Business Logic",
    };
}
