<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocX" Version="5.2.0" />
    <PackageReference Include="libclang.runtime.win-x64" Version="21.1.8" />
    <PackageReference Include="LLamaSharp" Version="0.27.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.27.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JBU.CodeLens.Shared\JBU.CodeLens.Shared.csproj" />
  </ItemGroup>

</Project>
