using Xceed.Document.NET;
using Xceed.Words.NET;

namespace CodeLensAI.Core.Export;

/// <summary>
/// Generates a professional .docx documentation file from scan results.
/// </summary>
public static class WordExporter
{
    private const string MonospaceFont = "Courier New";
    private const double MonospaceSize = 9d;

    /// <summary>
    /// Writes a complete project documentation document to <paramref name="outputPath"/>.
    /// </summary>
    /// <param name="explanationService">Optional local AI service used when <paramref name="includeAi"/> is true.</param>
    /// <param name="includeAi">When true, runs AI inference per method to enrich the document.</param>
    /// <param name="onProgress">Optional callback for export progress messages.</param>
    public static void Export(
        string outputPath,
        string projectFolderPath,
        List<ParseResult> parseResults,
        IExplanationService? explanationService = null,
        bool includeAi = false,
        Action<string>? onProgress = null,
        ProjectMetricsSnapshot? metrics = null)
    {
        var projectName = Path.GetFileName(
            projectFolderPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));

        using var document = DocX.Create(outputPath);

        document.AddFooters();
        document.Footers.Odd.PageNumbers = true;

        onProgress?.Invoke("Writing cover page…");
        WriteCoverPage(document, projectName, parseResults, includeAi, metrics);
        document.InsertParagraph().InsertPageBreakAfterSelf();

        onProgress?.Invoke("Writing table of contents…");
        WriteTableOfContents(document, parseResults);
        document.InsertParagraph().InsertPageBreakAfterSelf();

        var isFirstClassInDocument = true;
        foreach (var parseResult in parseResults)
        {
            onProgress?.Invoke($"Documenting {Path.GetFileName(parseResult.FilePath)}…");
            WriteFileSection(document, parseResult, ref isFirstClassInDocument, explanationService, includeAi, onProgress);
        }

        onProgress?.Invoke("Saving document…");
        document.Save();
    }

    private static void WriteCoverPage(
        DocX document,
        string projectName,
        List<ParseResult> parseResults,
        bool includeAi,
        ProjectMetricsSnapshot? metrics)
    {
        document.InsertParagraph(projectName)
            .FontSize(28)
            .Bold()
            .SpacingAfter(12d);

        document.InsertParagraph("Generated by CodeLens AI")
            .FontSize(14)
            .SpacingAfter(8d);

        document.InsertParagraph($"Generated on {DateTime.Now:MMMM d, yyyy 'at' h:mm tt}")
            .FontSize(11)
            .SpacingAfter(8d);

        document.InsertParagraph(includeAi ? "Includes AI-generated analysis" : "Parser metadata only (AI skipped)")
            .FontSize(11)
            .Italic()
            .SpacingAfter(24d);

        var stats = ComputeStats(parseResults);

        document.InsertParagraph("Summary")
            .Heading(HeadingType.Heading2)
            .SpacingAfter(8d);

        document.InsertParagraph($"Files scanned: {stats.FileCount}")
            .SpacingAfter(4d);
        document.InsertParagraph($"Classes found: {stats.ClassCount}")
            .SpacingAfter(4d);
        document.InsertParagraph($"Functions found: {stats.MethodCount}")
            .SpacingAfter(16d);

        if (metrics is not null)
        {
            document.InsertParagraph("SCIDE Project Metrics")
                .Heading(HeadingType.Heading2)
                .SpacingAfter(8d);

            document.InsertParagraph($"Namespaces: {metrics.TotalNamespaces}")
                .SpacingAfter(4d);
            document.InsertParagraph($"Relationships: {metrics.TotalRelationships}")
                .SpacingAfter(4d);
            document.InsertParagraph($"Maintainability index: {metrics.MaintainabilityIndex:F0}")
                .SpacingAfter(4d);
            document.InsertParagraph($"Average complexity: {metrics.AverageComplexity:F2} (max {metrics.MaxComplexity})")
                .SpacingAfter(16d);
        }

        document.InsertParagraph("Class Breakdown by Category")
            .Heading(HeadingType.Heading2)
            .SpacingAfter(8d);

        var table = document.AddTable(4, 2);
        table.Design = TableDesign.TableGrid;
        table.Alignment = Alignment.center;

        SetTableCell(table, 0, 0, "Category", bold: true);
        SetTableCell(table, 0, 1, "Count", bold: true);
        SetTableCell(table, 1, 0, "Business Logic");
        SetTableCell(table, 1, 1, stats.BusinessLogicCount.ToString());
        SetTableCell(table, 2, 0, "GUI Logic");
        SetTableCell(table, 2, 1, stats.GuiLogicCount.ToString());
        SetTableCell(table, 3, 0, "Utility");
        SetTableCell(table, 3, 1, stats.UtilityCount.ToString());

        document.InsertTable(table);
    }

    private static void WriteTableOfContents(DocX document, List<ParseResult> parseResults)
    {
        document.InsertParagraph("Table of Contents")
            .Heading(HeadingType.Heading1)
            .SpacingAfter(12d);

        foreach (var parseResult in parseResults)
        {
            var fileName = Path.GetFileName(parseResult.FilePath);
            var languageTag = LanguageFileExtensions.IsCppFile(parseResult.FilePath) ? "[C++]" : "[C#]";
            document.InsertParagraph($"{fileName} {languageTag}")
                .Bold()
                .SpacingAfter(2d);

            if (parseResult.Errors.Count > 0)
            {
                document.InsertParagraph($"    (parse error: {parseResult.Errors[0]})")
                    .Italic()
                    .SpacingAfter(6d);
                continue;
            }

            if (parseResult.Classes.Count == 0)
            {
                document.InsertParagraph("    (no classes)")
                    .Italic()
                    .SpacingAfter(6d);
                continue;
            }

            foreach (var classInfo in parseResult.Classes)
            {
                document.InsertParagraph($"    {classInfo.Name} [{DescribeCategory(classInfo.Category)}]")
                    .SpacingAfter(2d);
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }
    }

    private static void WriteFileSection(
        DocX document,
        ParseResult parseResult,
        ref bool isFirstClassInDocument,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress)
    {
        var fileName = Path.GetFileName(parseResult.FilePath);
        var isCpp = LanguageFileExtensions.IsCppFile(parseResult.FilePath);

        document.InsertParagraph(fileName)
            .Heading(HeadingType.Heading1)
            .SpacingBefore(12d)
            .SpacingAfter(4d);

        document.InsertParagraph(isCpp ? "[C++]" : "[C#]")
            .Bold()
            .SpacingAfter(8d);

        if (parseResult.Errors.Count > 0)
        {
            document.InsertParagraph($"Parse error: {string.Join("; ", parseResult.Errors)}")
                .SpacingAfter(16d);
            return;
        }

        if (parseResult.Classes.Count == 0)
        {
            document.InsertParagraph("(no classes found in this file)")
                .Italic()
                .SpacingAfter(16d);
            return;
        }

        for (var i = 0; i < parseResult.Classes.Count; i++)
        {
            if (!isFirstClassInDocument)
            {
                WriteClassDivider(document);
            }

            isFirstClassInDocument = false;
            WriteClassSection(document, parseResult.Classes[i], explanationService, includeAi, onProgress);
        }
    }

    private static void WriteClassSection(
        DocX document,
        ClassInfo classInfo,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress)
    {
        document.InsertParagraph(classInfo.Name)
            .Heading(HeadingType.Heading2)
            .SpacingBefore(8d)
            .SpacingAfter(6d);

        document.InsertParagraph($"[{DescribeCategory(classInfo.Category)}]")
            .SpacingAfter(4d);

        document.InsertParagraph(
                string.IsNullOrEmpty(classInfo.BaseClassName)
                    ? "Extends: No base class"
                    : $"Extends: {classInfo.BaseClassName}")
            .SpacingAfter(4d);

        document.InsertParagraph(
                classInfo.ImplementedInterfaces.Count > 0
                    ? $"Implements: {string.Join(", ", classInfo.ImplementedInterfaces)}"
                    : "Implements: None")
            .SpacingAfter(4d);

        document.InsertParagraph(
                classInfo.Dependencies.Count > 0
                    ? $"Depends on: {string.Join(", ", classInfo.Dependencies)}"
                    : "Depends on: None")
            .SpacingAfter(6d);

        if (!string.IsNullOrWhiteSpace(classInfo.XmlSummary))
        {
            document.InsertParagraph(classInfo.XmlSummary)
                .SpacingAfter(8d);
        }

        foreach (var method in classInfo.Methods)
        {
            WriteMethodSection(document, method, explanationService, includeAi, onProgress);
        }
    }

    private static void WriteMethodSection(
        DocX document,
        MethodInfo method,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress)
    {
        onProgress?.Invoke($"Documenting {method.ParentClass?.Name}.{method.Name}…");

        // One merged model call produces all five AI sections (instead of five sequential
        // round-trips). Null when AI is off or the model isn't ready.
        MethodAiDocumentation? aiDoc = includeAi && explanationService is { IsReady: true }
            ? explanationService.GenerateMethodDocumentation(method)
            : null;

        var signature = BuildSignature(method);

        document.InsertParagraph(signature)
            .Heading(HeadingType.Heading3)
            .Font(MonospaceFont)
            .FontSize(MonospaceSize)
            .SpacingBefore(10d)
            .SpacingAfter(4d);

        document.InsertParagraph($"Access: {method.AccessModifier}")
            .SpacingAfter(6d);

        document.InsertParagraph("Description")
            .Bold()
            .SpacingAfter(4d);

        if (!string.IsNullOrWhiteSpace(method.XmlSummary))
        {
            document.InsertParagraph(method.XmlSummary)
                .SpacingAfter(6d);
        }
        else if (aiDoc is { } briefDoc)
        {
            document.InsertParagraph(briefDoc.Brief)
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph("No description available.")
                .Italic()
                .SpacingAfter(6d);
        }

        document.InsertParagraph("Parameters")
            .Bold()
            .SpacingAfter(4d);

        if (method.Parameters.Count == 0)
        {
            document.InsertParagraph("This function takes no inputs.")
                .SpacingAfter(6d);
        }
        else
        {
            foreach (var parameter in method.Parameters)
            {
                var (type, name) = SplitParameter(parameter);
                var paramLine = document.InsertParagraph()
                    .SpacingAfter(2d);
                paramLine.Append($"{type} ").Font(MonospaceFont).FontSize(MonospaceSize);
                paramLine.Append(name).Bold();

                if (method.XmlDocTags.TryGetValue($"param:{name}", out var paramDoc))
                {
                    document.InsertParagraph(paramDoc)
                        .SpacingAfter(4d);
                }
                else
                {
                    document.InsertParagraph("No description available.")
                        .Italic()
                        .SpacingAfter(4d);
                }
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        document.InsertParagraph("Returns")
            .Bold()
            .SpacingAfter(4d);

        var returnsLine = document.InsertParagraph()
            .SpacingAfter(2d);
        returnsLine.Append(method.ReturnType).Font(MonospaceFont).FontSize(MonospaceSize);

        if (method.XmlDocTags.TryGetValue("returns", out var returnsDoc))
        {
            document.InsertParagraph(returnsDoc)
                .SpacingAfter(6d);
        }
        else if (!string.Equals(method.ReturnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            document.InsertParagraph("No return description available.")
                .Italic()
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(6d);
        }

        document.InsertParagraph("Error Situations")
            .Bold()
            .SpacingAfter(4d);

        var hasOrganicErrors = false;
        foreach (var exception in method.ThrownExceptions)
        {
            hasOrganicErrors = true;
            var doc = FindExceptionDescription(method, exception);
            document.InsertParagraph($"• {exception}: {doc ?? "Thrown in method body"}")
                .SpacingAfter(2d);
        }

        foreach (var tag in method.XmlDocTags.Where(t => t.Key.StartsWith("exception:", StringComparison.OrdinalIgnoreCase)))
        {
            hasOrganicErrors = true;
            var type = tag.Key["exception:".Length..];
            document.InsertParagraph($"• {type}: {tag.Value}")
                .SpacingAfter(2d);
        }

        if (!hasOrganicErrors)
        {
            document.InsertParagraph("No exceptions detected in source code.")
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        if (method.CachedAnalysis is { } cached)
        {
            WriteDeterministicAnalysisSection(document, cached);
        }

        if (aiDoc is { } sections)
        {
            WriteBulletSection(document, "Pre & Post Conditions", sections.PrePostConditions);
            WriteBulletSection(document, "Design Constraints", sections.DesignConstraints);
            WriteBulletSection(document, "AI Error Analysis", sections.ErrorAnalysis);

            document.InsertParagraph("AI Explanation")
                .Bold()
                .SpacingAfter(4d);
            document.InsertParagraph(sections.Explanation)
                .SpacingAfter(12d);
        }
    }

    private static string? FindExceptionDescription(MethodInfo method, string exceptionType)
    {
        foreach (var tag in method.XmlDocTags)
        {
            if (!tag.Key.StartsWith("exception:", StringComparison.OrdinalIgnoreCase)) continue;
            var keyType = tag.Key["exception:".Length..];
            if (string.Equals(keyType, exceptionType, StringComparison.OrdinalIgnoreCase)
                || keyType.EndsWith(exceptionType, StringComparison.OrdinalIgnoreCase))
                return tag.Value;
        }

        return null;
    }

    private static void WriteDeterministicAnalysisSection(DocX document, MethodAnalysis analysis)
    {
        var prePost = new List<string>();
        prePost.AddRange(analysis.Preconditions.Select(p => p.Description));
        prePost.AddRange(analysis.Postconditions.Select(p => p.Description));
        prePost.AddRange(analysis.StateChanges.Select(s => s.Description));

        if (prePost.Count > 0)
        {
            WriteBulletSection(document, "Pre & Post Conditions (Deterministic)",
                string.Join('\n', prePost.Select(p => $"- {p}")));
        }

        if (analysis.ExecutionSteps.Count > 0)
        {
            document.InsertParagraph("Execution Flow (Deterministic)")
                .Bold()
                .SpacingBefore(8d)
                .SpacingAfter(4d);

            foreach (var step in analysis.ExecutionSteps)
            {
                document.InsertParagraph($"{step.StepNumber}. {step.Description}")
                    .SpacingAfter(2d);
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        if (analysis.DesignConstraints.Count > 0)
        {
            WriteBulletSection(document, "Design Requirements (Deterministic)",
                string.Join('\n', analysis.DesignConstraints.Select(c => $"- {c.Description}")));
        }
    }

    private static void WriteBulletSection(DocX document, string heading, string content)
    {
        document.InsertParagraph(heading)
            .Bold()
            .SpacingBefore(8d)
            .SpacingAfter(4d);

        var hasBullets = false;
        foreach (var rawLine in content.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var line = rawLine.TrimStart('-', '•', '*', ' ');
            if (string.IsNullOrWhiteSpace(line)) continue;
            hasBullets = true;
            document.InsertParagraph($"• {line}")
                .SpacingAfter(2d);
        }

        if (!hasBullets)
        {
            document.InsertParagraph(content)
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }
    }

    private static void WriteClassDivider(DocX document)
    {
        document.InsertParagraph("────────────────────────────────────────")
            .FontSize(8d)
            .SpacingBefore(16d)
            .SpacingAfter(16d);
    }

    private static void SetTableCell(Table table, int row, int column, string text, bool bold = false)
    {
        var paragraph = table.Rows[row].Cells[column].Paragraphs[0];
        paragraph.RemoveText(0);
        var formatted = paragraph.Append(text);
        if (bold)
        {
            formatted.Bold();
        }
    }

    private static (int FileCount, int ClassCount, int MethodCount, int BusinessLogicCount, int GuiLogicCount, int UtilityCount)
        ComputeStats(List<ParseResult> parseResults)
    {
        var classCount = 0;
        var methodCount = 0;
        var businessLogic = 0;
        var guiLogic = 0;
        var utility = 0;

        foreach (var parseResult in parseResults)
        {
            foreach (var classInfo in parseResult.Classes)
            {
                classCount++;
                methodCount += classInfo.Methods.Count;

                switch (classInfo.Category)
                {
                    case CodeCategory.GuiLogic:
                        guiLogic++;
                        break;
                    case CodeCategory.Utility:
                        utility++;
                        break;
                    default:
                        businessLogic++;
                        break;
                }
            }
        }

        return (parseResults.Count, classCount, methodCount, businessLogic, guiLogic, utility);
    }

    private static string BuildSignature(MethodInfo method)
    {
        var parameters = method.Parameters.Count > 0
            ? string.Join(", ", method.Parameters)
            : string.Empty;
        return $"{method.ReturnType} {method.Name}({parameters})";
    }

    private static (string Type, string Name) SplitParameter(string parameter)
    {
        var lastSpace = parameter.LastIndexOf(' ');
        if (lastSpace <= 0 || lastSpace >= parameter.Length - 1)
        {
            return (parameter, "value");
        }

        return (parameter[..lastSpace].Trim(), parameter[(lastSpace + 1)..].Trim());
    }

    private static string DescribeCategory(CodeCategory category) => category switch
    {
        CodeCategory.GuiLogic => "GUI Logic",
        CodeCategory.Utility => "Utility",
        _ => "Business Logic",
    };
}
