using System.Globalization;

using Xceed.Document.NET;
using Xceed.Words.NET;

namespace JBU.CodeLens.Core.Export;

/// <summary>
/// Generates a professional .docx documentation file from scan results.
/// </summary>
public static class WordExporter
{
    private const string MonospaceFont = "Courier New";
    private const double MonospaceSize = 9d;

    /// <summary>
    /// Writes a complete project documentation document to <paramref name="outputPath"/>.
    /// </summary>
    /// <param name="explanationService">Optional local AI service used when <paramref name="includeAi"/> is true.</param>
    /// <param name="includeAi">When true, runs AI inference per method to enrich the document.</param>
    /// <param name="onProgress">Optional callback for export progress messages.</param>
    public static void Export(
        string outputPath,
        string projectFolderPath,
        List<ParseResult> parseResults,
        IExplanationService? explanationService = null,
        bool includeAi = false,
        Action<string>? onProgress = null,
        ProjectMetricsSnapshot? metrics = null,
        CancellationToken cancellationToken = default)
    {
        // Generation (especially with AI) can take minutes and fail midway; writing to a temp
        // file and moving on success guarantees the chosen path never holds a corrupt .docx —
        // including on cancellation, which propagates out of ExportCore before the final move.
        AtomicFileWriter.Write(outputPath, tempPath =>
            ExportCore(tempPath, projectFolderPath, parseResults, explanationService, includeAi, onProgress, metrics, cancellationToken));
    }

    private static void ExportCore(
        string outputPath,
        string projectFolderPath,
        List<ParseResult> parseResults,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress,
        ProjectMetricsSnapshot? metrics,
        CancellationToken cancellationToken)
    {
        var projectName = Path.GetFileName(
            projectFolderPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));

        using var document = DocX.Create(outputPath);

        document.AddFooters();
        document.Footers.Odd.PageNumbers = true;

        onProgress?.Invoke("Writing cover page…");
        WriteCoverPage(document, projectName, parseResults, includeAi, metrics);
        document.InsertParagraph().InsertPageBreakAfterSelf();

        onProgress?.Invoke("Writing table of contents…");
        WriteTableOfContents(document, parseResults);
        document.InsertParagraph().InsertPageBreakAfterSelf();

        var methodProgress = new MethodProgress
        {
            Total = parseResults.Sum(r => r.Classes.Sum(c => c.Methods.Count)),
        };

        var isFirstClassInDocument = true;
        foreach (var parseResult in parseResults)
        {
            cancellationToken.ThrowIfCancellationRequested();
            onProgress?.Invoke($"Documenting {Path.GetFileName(parseResult.FilePath)}…");
            WriteFileSection(document, parseResult, ref isFirstClassInDocument, explanationService, includeAi, onProgress, methodProgress, cancellationToken);
        }

        onProgress?.Invoke("Saving document…");
        document.Save();
    }

    /// <summary>
    /// Running method counter for export progress messages ("method k of n") — the count that
    /// actually tracks elapsed time during AI exports, where each method costs an inference call.
    /// </summary>
    private sealed class MethodProgress
    {
        public int Total { get; init; }
        public int Done { get; set; }
    }

    private static void WriteCoverPage(
        DocX document,
        string projectName,
        List<ParseResult> parseResults,
        bool includeAi,
        ProjectMetricsSnapshot? metrics)
    {
        document.InsertParagraph(projectName)
            .FontSize(28)
            .Bold()
            .SpacingAfter(12d);

        document.InsertParagraph("Generated by JBU CodeLens")
            .FontSize(14)
            .SpacingAfter(8d);

        document.InsertParagraph($"Generated on {DateTime.Now:MMMM d, yyyy 'at' h:mm tt}")
            .FontSize(11)
            .SpacingAfter(8d);

        document.InsertParagraph(includeAi ? "Includes AI-generated analysis" : "Parser metadata only (AI skipped)")
            .FontSize(11)
            .Italic()
            .SpacingAfter(24d);

        var stats = ComputeStats(parseResults);

        document.InsertParagraph("Summary")
            .Heading(HeadingType.Heading2)
            .SpacingAfter(8d);

        document.InsertParagraph($"Files scanned: {stats.FileCount}")
            .SpacingAfter(4d);
        document.InsertParagraph($"Classes found: {stats.ClassCount}")
            .SpacingAfter(4d);
        document.InsertParagraph($"Functions found: {stats.MethodCount}")
            .SpacingAfter(16d);

        if (metrics is not null)
        {
            document.InsertParagraph("SCIDE Project Metrics")
                .Heading(HeadingType.Heading2)
                .SpacingAfter(8d);

            document.InsertParagraph($"Namespaces: {metrics.TotalNamespaces}")
                .SpacingAfter(4d);
            document.InsertParagraph($"Relationships: {metrics.TotalRelationships}")
                .SpacingAfter(4d);
            document.InsertParagraph($"Maintainability index: {metrics.MaintainabilityIndex:F0}")
                .SpacingAfter(4d);
            document.InsertParagraph($"Average complexity: {metrics.AverageComplexity:F2} (max {metrics.MaxComplexity})")
                .SpacingAfter(16d);
        }

        document.InsertParagraph("Class Breakdown by Category")
            .Heading(HeadingType.Heading2)
            .SpacingAfter(8d);

        var table = document.AddTable(4, 2);
        table.Design = TableDesign.TableGrid;
        table.Alignment = Alignment.center;

        SetTableCell(table, 0, 0, "Category", bold: true);
        SetTableCell(table, 0, 1, "Count", bold: true);
        SetTableCell(table, 1, 0, "Business Logic");
        SetTableCell(table, 1, 1, stats.BusinessLogicCount.ToString(CultureInfo.InvariantCulture));
        SetTableCell(table, 2, 0, "GUI Logic");
        SetTableCell(table, 2, 1, stats.GuiLogicCount.ToString(CultureInfo.InvariantCulture));
        SetTableCell(table, 3, 0, "Utility");
        SetTableCell(table, 3, 1, stats.UtilityCount.ToString(CultureInfo.InvariantCulture));

        document.InsertTable(table);
    }

    private static void WriteTableOfContents(DocX document, List<ParseResult> parseResults)
    {
        document.InsertParagraph("Table of Contents")
            .Heading(HeadingType.Heading1)
            .SpacingAfter(12d);

        foreach (var parseResult in parseResults)
        {
            var fileName = Path.GetFileName(parseResult.FilePath);
            var languageTag = LanguageFileExtensions.IsCppFile(parseResult.FilePath) ? "[C++]" : "[C#]";
            document.InsertParagraph($"{fileName} {languageTag}")
                .Bold()
                .SpacingAfter(2d);

            if (parseResult.Errors.Count > 0)
            {
                document.InsertParagraph($"    (parse error: {parseResult.Errors[0]})")
                    .Italic()
                    .SpacingAfter(6d);
                continue;
            }

            if (parseResult.Classes.Count == 0)
            {
                document.InsertParagraph("    (no classes)")
                    .Italic()
                    .SpacingAfter(6d);
                continue;
            }

            foreach (var classInfo in parseResult.Classes)
            {
                document.InsertParagraph($"    {classInfo.Name} [{DescribeCategory(classInfo.Category)}]")
                    .SpacingAfter(2d);
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }
    }

    private static void WriteFileSection(
        DocX document,
        ParseResult parseResult,
        ref bool isFirstClassInDocument,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress,
        MethodProgress methodProgress,
        CancellationToken cancellationToken)
    {
        var fileName = Path.GetFileName(parseResult.FilePath);
        var isCpp = LanguageFileExtensions.IsCppFile(parseResult.FilePath);

        document.InsertParagraph(fileName)
            .Heading(HeadingType.Heading1)
            .SpacingBefore(12d)
            .SpacingAfter(4d);

        document.InsertParagraph(isCpp ? "[C++]" : "[C#]")
            .Bold()
            .SpacingAfter(8d);

        if (parseResult.Errors.Count > 0)
        {
            document.InsertParagraph($"Parse error: {string.Join("; ", parseResult.Errors)}")
                .SpacingAfter(16d);
            return;
        }

        if (parseResult.Classes.Count == 0)
        {
            document.InsertParagraph("(no classes found in this file)")
                .Italic()
                .SpacingAfter(16d);
            return;
        }

        for (var i = 0; i < parseResult.Classes.Count; i++)
        {
            if (!isFirstClassInDocument)
            {
                WriteClassDivider(document);
            }

            isFirstClassInDocument = false;
            WriteClassSection(document, parseResult.Classes[i], explanationService, includeAi, onProgress, methodProgress, cancellationToken);
        }
    }

    private static void WriteClassSection(
        DocX document,
        ClassInfo classInfo,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress,
        MethodProgress methodProgress,
        CancellationToken cancellationToken)
    {
        document.InsertParagraph(classInfo.Name)
            .Heading(HeadingType.Heading2)
            .SpacingBefore(8d)
            .SpacingAfter(6d);

        document.InsertParagraph($"[{DescribeCategory(classInfo.Category)}]")
            .SpacingAfter(4d);

        document.InsertParagraph(
                string.IsNullOrEmpty(classInfo.BaseClassName)
                    ? "Extends: No base class"
                    : $"Extends: {classInfo.BaseClassName}")
            .SpacingAfter(4d);

        document.InsertParagraph(
                classInfo.ImplementedInterfaces.Count > 0
                    ? $"Implements: {string.Join(", ", classInfo.ImplementedInterfaces)}"
                    : "Implements: None")
            .SpacingAfter(4d);

        document.InsertParagraph(
                classInfo.Dependencies.Count > 0
                    ? $"Depends on: {string.Join(", ", classInfo.Dependencies)}"
                    : "Depends on: None")
            .SpacingAfter(6d);

        var classSummary = !string.IsNullOrWhiteSpace(classInfo.XmlSummary)
            ? classInfo.XmlSummary
            : classInfo.InferredDescription;
        if (!string.IsNullOrWhiteSpace(classSummary))
        {
            document.InsertParagraph(classSummary)
                .SpacingAfter(8d);
        }

        foreach (var method in classInfo.Methods)
        {
            cancellationToken.ThrowIfCancellationRequested();
            WriteMethodSection(document, method, explanationService, includeAi, onProgress, methodProgress, cancellationToken);
        }
    }

    private static void WriteMethodSection(
        DocX document,
        MethodInfo method,
        IExplanationService? explanationService,
        bool includeAi,
        Action<string>? onProgress,
        MethodProgress methodProgress,
        CancellationToken cancellationToken)
    {
        methodProgress.Done++;
        onProgress?.Invoke(
            $"Documenting method {methodProgress.Done}/{methodProgress.Total} — {method.ParentClass?.Name}.{method.Name}…");

        // One merged model call produces all five AI sections (instead of five sequential
        // round-trips). Null when AI is off or the model isn't ready.
        MethodAiDocumentation? aiDoc = includeAi && explanationService is { IsReady: true }
            ? explanationService.GenerateMethodDocumentation(method, cancellationToken)
            : null;

        var signature = BuildSignature(method);

        document.InsertParagraph(signature)
            .Heading(HeadingType.Heading3)
            .Font(MonospaceFont)
            .FontSize(MonospaceSize)
            .SpacingBefore(10d)
            .SpacingAfter(4d);

        document.InsertParagraph($"Access: {method.AccessModifier}")
            .SpacingAfter(6d);

        document.InsertParagraph("Description")
            .Bold()
            .SpacingAfter(4d);

        if (!string.IsNullOrWhiteSpace(method.XmlSummary))
        {
            document.InsertParagraph(method.XmlSummary)
                .SpacingAfter(6d);
        }
        else if (aiDoc is { } briefDoc)
        {
            document.InsertParagraph(briefDoc.Brief)
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph("No description available.")
                .Italic()
                .SpacingAfter(6d);
        }

        document.InsertParagraph("Parameters")
            .Bold()
            .SpacingAfter(4d);

        if (method.Parameters.Count == 0)
        {
            document.InsertParagraph("This function takes no inputs.")
                .SpacingAfter(6d);
        }
        else
        {
            foreach (var parameter in method.Parameters)
            {
                var (type, name) = SplitParameter(parameter);
                var paramLine = document.InsertParagraph()
                    .SpacingAfter(2d);
                paramLine.Append($"{type} ").Font(MonospaceFont).FontSize(MonospaceSize);
                paramLine.Append(name).Bold();

                if (method.XmlDocTags.TryGetValue($"param:{name}", out var paramDoc))
                {
                    document.InsertParagraph(paramDoc)
                        .SpacingAfter(4d);
                }
                else
                {
                    document.InsertParagraph("No description available.")
                        .Italic()
                        .SpacingAfter(4d);
                }
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        document.InsertParagraph("Returns")
            .Bold()
            .SpacingAfter(4d);

        var returnsLine = document.InsertParagraph()
            .SpacingAfter(2d);
        returnsLine.Append(method.ReturnType).Font(MonospaceFont).FontSize(MonospaceSize);

        if (method.XmlDocTags.TryGetValue("returns", out var returnsDoc))
        {
            document.InsertParagraph(returnsDoc)
                .SpacingAfter(6d);
        }
        else if (!string.Equals(method.ReturnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            document.InsertParagraph("No return description available.")
                .Italic()
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(6d);
        }

        document.InsertParagraph("Error Situations")
            .Bold()
            .SpacingAfter(4d);

        var hasOrganicErrors = false;
        foreach (var exception in method.ThrownExceptions)
        {
            hasOrganicErrors = true;
            var doc = FindExceptionDescription(method, exception);
            document.InsertParagraph($"• {exception}: {doc ?? "Thrown in method body"}")
                .SpacingAfter(2d);
        }

        foreach (var tag in method.XmlDocTags.Where(t => t.Key.StartsWith("exception:", StringComparison.OrdinalIgnoreCase)))
        {
            hasOrganicErrors = true;
            var type = tag.Key["exception:".Length..];
            document.InsertParagraph($"• {type}: {tag.Value}")
                .SpacingAfter(2d);
        }

        if (!hasOrganicErrors)
        {
            document.InsertParagraph("No exceptions detected in source code.")
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        // The "Pre & Post Conditions" and "Design Constraints" headings are part of the
        // mandatory six-heading format and must appear for every method, in order, regardless
        // of whether the AI ran or produced usable output. Deterministic analysis is always
        // listed first (it never hallucinates); AI bullets extend it; an explicit placeholder
        // covers the nothing-detected case.
        var prePostLines = new List<string>();
        var designLines = new List<string>();
        if (method.CachedAnalysis is { } cached)
        {
            prePostLines.AddRange(cached.Preconditions.Select(p => p.Description));
            prePostLines.AddRange(cached.Postconditions.Select(p => p.Description));
            prePostLines.AddRange(cached.StateChanges.Select(s => s.Description));
            designLines.AddRange(cached.DesignConstraints.Select(c => c.Description));
        }

        if (aiDoc is { UsedAi: true } ai)
        {
            // The AI conditions arrive with PRE:/POST: markers; qualify each bullet so the reader
            // can tell the two apart, and so the raw markers never reach the document as bullets.
            var groups = PrePostConditionText.Split(ai.PrePostConditions);
            if (groups.IsGrouped)
            {
                prePostLines.AddRange(groups.Preconditions.Select(p => $"Precondition: {p}"));
                prePostLines.AddRange(groups.Postconditions.Select(p => $"Postcondition: {p}"));
                prePostLines.AddRange(groups.Ungrouped);
            }
            else
            {
                prePostLines.AddRange(SplitBulletLines(ai.PrePostConditions));
            }

            designLines.AddRange(SplitBulletLines(ai.DesignConstraints));
        }

        WriteMandatoryBulletSection(document, "Pre & Post Conditions", prePostLines,
            "None detected from source analysis.");
        WriteMandatoryBulletSection(document, "Design Constraints", designLines,
            "None detected from source analysis.");

        if (method.CachedAnalysis is { ExecutionSteps.Count: > 0 } withSteps)
        {
            document.InsertParagraph("Execution Flow (Deterministic)")
                .Bold()
                .SpacingBefore(8d)
                .SpacingAfter(4d);

            foreach (var step in withSteps.ExecutionSteps)
            {
                document.InsertParagraph($"{step.StepNumber}. {step.Description}")
                    .SpacingAfter(2d);
            }

            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }

        if (aiDoc is { } sections)
        {
            WriteBulletSection(document, "AI Error Analysis", sections.ErrorAnalysis);

            document.InsertParagraph("AI Explanation")
                .Bold()
                .SpacingAfter(4d);
            document.InsertParagraph(sections.Explanation)
                .SpacingAfter(12d);
        }
    }

    /// <summary>
    /// Splits AI bullet output into clean lines, dropping bullet markers and blanks. Bracketed
    /// strings (error/unavailable messages) yield nothing, so they can never surface as a fake
    /// documentation bullet.
    /// </summary>
    private static IEnumerable<string> SplitBulletLines(string content)
    {
        if (string.IsNullOrWhiteSpace(content) || content.StartsWith('['))
        {
            yield break;
        }

        foreach (var rawLine in content.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var line = rawLine.TrimStart('-', '•', '*', ' ');
            if (!string.IsNullOrWhiteSpace(line))
            {
                yield return line;
            }
        }
    }

    /// <summary>
    /// Writes one of the always-present documentation headings with its bullets, or the
    /// placeholder text when no content is available — the heading itself is never omitted.
    /// </summary>
    private static void WriteMandatoryBulletSection(
        DocX document,
        string heading,
        List<string> lines,
        string placeholder)
    {
        document.InsertParagraph(heading)
            .Bold()
            .SpacingBefore(8d)
            .SpacingAfter(4d);

        if (lines.Count == 0)
        {
            document.InsertParagraph(placeholder)
                .Italic()
                .SpacingAfter(6d);
            return;
        }

        foreach (var line in lines.Distinct(StringComparer.OrdinalIgnoreCase))
        {
            document.InsertParagraph($"• {line}")
                .SpacingAfter(2d);
        }

        document.InsertParagraph(string.Empty).SpacingAfter(4d);
    }

    private static string? FindExceptionDescription(MethodInfo method, string exceptionType) =>
        MethodDocumentation.FindExceptionDescription(method, exceptionType);

    private static void WriteBulletSection(DocX document, string heading, string content)
    {
        document.InsertParagraph(heading)
            .Bold()
            .SpacingBefore(8d)
            .SpacingAfter(4d);

        var hasBullets = false;
        foreach (var rawLine in content.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var line = rawLine.TrimStart('-', '•', '*', ' ');
            if (string.IsNullOrWhiteSpace(line)) continue;
            hasBullets = true;
            document.InsertParagraph($"• {line}")
                .SpacingAfter(2d);
        }

        if (!hasBullets)
        {
            document.InsertParagraph(content)
                .SpacingAfter(6d);
        }
        else
        {
            document.InsertParagraph(string.Empty).SpacingAfter(4d);
        }
    }

    private static void WriteClassDivider(DocX document)
    {
        document.InsertParagraph("────────────────────────────────────────")
            .FontSize(8d)
            .SpacingBefore(16d)
            .SpacingAfter(16d);
    }

    private static void SetTableCell(Table table, int row, int column, string text, bool bold = false)
    {
        var paragraph = table.Rows[row].Cells[column].Paragraphs[0];
        paragraph.RemoveText(0);
        var formatted = paragraph.Append(text);
        if (bold)
        {
            formatted.Bold();
        }
    }

    private static (int FileCount, int ClassCount, int MethodCount, int BusinessLogicCount, int GuiLogicCount, int UtilityCount)
        ComputeStats(List<ParseResult> parseResults)
    {
        var classCount = 0;
        var methodCount = 0;
        var businessLogic = 0;
        var guiLogic = 0;
        var utility = 0;

        foreach (var parseResult in parseResults)
        {
            foreach (var classInfo in parseResult.Classes)
            {
                classCount++;
                methodCount += classInfo.Methods.Count;

                switch (classInfo.Category)
                {
                    case CodeCategory.GuiLogic:
                        guiLogic++;
                        break;
                    case CodeCategory.Utility:
                        utility++;
                        break;
                    default:
                        businessLogic++;
                        break;
                }
            }
        }

        return (parseResults.Count, classCount, methodCount, businessLogic, guiLogic, utility);
    }

    private static string BuildSignature(MethodInfo method)
    {
        var parameters = method.Parameters.Count > 0
            ? string.Join(", ", method.Parameters)
            : string.Empty;
        return $"{method.ReturnType} {method.Name}({parameters})";
    }

    private static (string Type, string Name) SplitParameter(string parameter)
    {
        var lastSpace = parameter.LastIndexOf(' ');
        if (lastSpace <= 0 || lastSpace >= parameter.Length - 1)
        {
            return (parameter, "value");
        }

        return (parameter[..lastSpace].Trim(), parameter[(lastSpace + 1)..].Trim());
    }

    private static string DescribeCategory(CodeCategory category) => category switch
    {
        CodeCategory.GuiLogic => "GUI Logic",
        CodeCategory.Utility => "Utility",
        _ => "Business Logic",
    };
}
